apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: kul
  labels:
    type: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: application
    nodePort: 30000 # range is 30000 - 32767
    name: application
    protocol: TCP
  selector:
    type: frontend
